name: Build and Push Docker Image

# 1. The Trigger: When does this run?
on:
  push:
    branches:
      - main

# 2. The Machine: What computer runs this?
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 3. The Instructions: What does it do?
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate a Unique Image Tag
      id: generate_tag
      # This takes the first 7 characters of your Git commit ID to use as the version number
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # It tags the image with BOTH the unique Git SHA and "latest"
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ steps.generate_tag.outputs.sha_short }}
          ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest