name: Build and Push Docker Image

# 1. The Trigger: When does this run?
on:
  push:
    branches:
      - main

# 2. The Machine: What computer runs this?
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 3. The Instructions: What does it do?
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate a Unique Image Tag
      id: generate_tag
      # This takes the first 7 characters of your Git commit ID to use as the version number
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # It tags the image with BOTH the unique Git SHA and "latest"
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ steps.generate_tag.outputs.sha_short }}
          ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest

    # --- ADD THESE NEW STEPS TO THE BOTTOM OF YOUR FILE ---

    - name: Checkout the GitOps Config Repository
      uses: actions/checkout@v4
      with:
        # NOTE: Replace 'neyo55' for your GitHub username and 'argocd-fastapi-config' for your GitOps repo name!
        repository: neyo55/argocd-fastapi-config
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops-repo

    - name: Update Kubernetes Manifest with new Image Tag
      run: |
        cd gitops-repo
        
        # 1. Use 'sed' to find the old image tag and replace it with the new Git SHA tag
        # Replace 'neyo55' with your Docker Hub username!
        sed -i "s|image: neyo55/fastapi-app:.*|image: neyo55/fastapi-app:${{ steps.generate_tag.outputs.sha_short }}|g" deployment.yaml
        
        # 2. Tell Git who is making this automated commit
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # 3. Commit and push the changes back to GitHub
        git add deployment.yaml
        git commit -m "Auto-update image tag to ${{ steps.generate_tag.outputs.sha_short }}"
        git push origin main